In [1]:
import numpy as np 
import array

In [2]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([1,2,3,4,5,"ansh", 4+8j])

array(['1', '2', '3', '4', '5', 'ansh', '(4+8j)'], dtype='<U64')

In [5]:
np.array([1,2,3,4,5.1])

array([1. , 2. , 3. , 4. , 5.1])

- Numpy converts int to float or string even if one of them is float/string.

In [7]:
np.array([[1,3], [3,4]])

array([[1, 3],
       [3, 4]])

In [8]:
np.array([[1,3], [3,4], [6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [9]:
np.array([[[1,2],[3,4]],[[4,5],[6,7]]])

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

In [10]:
np.array([1,2,3], dtype = complex) #Type conversion

array([1.+0.j, 2.+0.j, 3.+0.j])

In [17]:
arr = np.array([(1,2),(4,5)], dtype = [("a",'<i4'),("b", '<i8')])
type(arr[0][0])

numpy.int32

In [18]:
type(arr[0][1])

numpy.int64

In [19]:
np.mat(arr)

matrix([[(1, 2), (4, 5)]], dtype=[('a', '<i4'), ('b', '<i8')])

In [20]:
np.asanyarray(arr)

array([(1, 2), (4, 5)], dtype=[('a', '<i4'), ('b', '<i8')])

In [21]:
issubclass(np.ndarray, np.matrix)

False

In [22]:
issubclass(np.matrix, np.ndarray)

True

In [27]:
arr = np.array([1,2,3,4,5])

In [28]:
a = arr

In [29]:
b = np.copy(a)

In [31]:
arr[1] = 60

In [32]:
print(a,b)

[ 1 60  3  4  5] [1 2 3 4 5]


- array are mutable and **shallow** Copy  = np.copy()

In [33]:
arr[-1]

5

In [34]:
for i in arr:
    print(i)

1
60
3
4
5


In [35]:
np.fromfunction(lambda i,j: i/j, (3,3))

/var/folders/xp/jy5j7tmd2c7bsktzm4pdpxm40000gn/T/ipykernel_54754/2105401307.py:1: RuntimeWarning: divide by zero encountered in divide
  np.fromfunction(lambda i,j: i/j, (3,3))
/var/folders/xp/jy5j7tmd2c7bsktzm4pdpxm40000gn/T/ipykernel_54754/2105401307.py:1: RuntimeWarning: invalid value encountered in divide
  np.fromfunction(lambda i,j: i/j, (3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [36]:
np.fromfunction(lambda i,j: i+j, (3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [40]:
a=[i+i for i in range(5)]
print(a)

[0, 2, 4, 6, 8]


In [43]:
(i+i for i in range(5))

<generator object <genexpr> at 0x11751f1d0>

In [45]:
def test(x):
    yield x

In [46]:
test(5)

<generator object test at 0x117a00c40>

- range is also a generator function

In [47]:
np.fromiter(range(5), dtype=int)

array([0, 1, 2, 3, 4])

In [52]:
np.fromstring('1 2 3 5', sep=' ')

array([1., 2., 3., 5.])

In [59]:
np.fromstring('12,35', sep=',', dtype=int)

array([12, 35])

In [61]:
l = [1,2,3,4,5,6,7,8]
arr = np.array(l)
type(arr)

numpy.ndarray

In [63]:
l = [[1,2,3],[4,5,6],[7,8,0]]
arr1 = np.array(l)
type(arr1)

numpy.ndarray

In [67]:
arr1.ndim #Dimension of array

2

In [68]:
arr.ndim

1

In [69]:
arr1.shape

(3, 3)

In [70]:
arr1.size

9

In [71]:
np.arange(5.1) #for float

array([0., 1., 2., 3., 4., 5.])

In [72]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [74]:
np.linspace(1,2,5) # 5 sections on number line between 1 and 2 in gaussian distribution

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

- 5 sections on number line between 1 and 2 in gaussian distribution
- By default: 50

In [75]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [77]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
np.zeros((2,5,4)) # 3D Array

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [79]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [80]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [81]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [82]:
np.empty((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [85]:
np.eye(4) # Identity Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [91]:
np.linspace(start=2, stop=4, num=5, endpoint=False, axis=0)

array([2. , 2.4, 2.8, 3.2, 3.6])

In [98]:
np.linspace(start = [2,4,3,5],stop = 5, num=5, endpoint=False, axis=0)

array([[2. , 4. , 3. , 5. ],
       [2.6, 4.2, 3.4, 5. ],
       [3.2, 4.4, 3.8, 5. ],
       [3.8, 4.6, 4.2, 5. ],
       [4.4, 4.8, 4.6, 5. ]])

In [99]:
np.logspace(2,3,4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [104]:
d = np.logspace(1,3,5, endpoint=False)
d.ndim

1

In [105]:
d.shape

(5,)

In [107]:
d.reshape(5,1)

array([[ 10.        ],
       [ 25.11886432],
       [ 63.09573445],
       [158.48931925],
       [398.10717055]])

- Used mostly to reshape arrays/Dataframes.

In [109]:
d.reshape(1,5)

array([[ 10.        ,  25.11886432,  63.09573445, 158.48931925,
        398.10717055]])

In [110]:
np.random.rand(3)

array([0.53659502, 0.5871061 , 0.56662104])

In [119]:
np.random.randn(2,2,3)

array([[[-0.20882395,  0.2176581 , -0.49736977],
        [-1.35049883, -1.34021961,  1.89905781]],

       [[-1.88905485,  0.52349763,  0.49293234],
        [-0.11301578, -0.74679406,  0.12883732]]])

- randn - generates data based on standard normal distribution.
- rand - generates data based on uniform distribution.

In [121]:
a = np.random.randint(1,50, (3,3))
a

array([[49, 11, 46],
       [ 8, 34, 18],
       [20, 45, 15]])

In [123]:
a.reshape(1,9) # can also write -1 in place of 9 and it will do the same thing

array([[49, 11, 46,  8, 34, 18, 20, 45, 15]])

In [124]:
a.min()

8

In [125]:
a.max()

49

In [127]:
arr = np.random.randint(1,50, (4,4))
arr

array([[17, 30, 13, 13],
       [29,  2, 12, 41],
       [24, 33, 32, 40],
       [22, 47, 15,  7]])

In [129]:
# Print 32 to 7
arr[2:,2:]

array([[32, 40],
       [15,  7]])

In [140]:
# Print 2nd and last col
arr[:,(1,3)]

array([[30, 13],
       [ 2, 41],
       [33, 40],
       [47,  7]])

In [144]:
# Print the diagonal
[arr[i,i] for i in range(arr.shape[0])]

[17, 2, 32, 7]

In [145]:
arr*arr

array([[ 289,  900,  169,  169],
       [ 841,    4,  144, 1681],
       [ 576, 1089, 1024, 1600],
       [ 484, 2209,  225,   49]])

In [147]:
arr@arr # Matrix multiplication

array([[1757, 1610, 1192, 2062],
       [1741, 3197, 1400, 1226],
       [3013, 3722, 2332, 3225],
       [2251, 1578, 1435, 2862]])

In [148]:
arr**2 # Square

array([[ 289,  900,  169,  169],
       [ 841,    4,  144, 1681],
       [ 576, 1089, 1024, 1600],
       [ 484, 2209,  225,   49]])

In [152]:
a1 = np.zeros((3,4))  # Broadcasting
a2 = np.array([1,2,3,6])
print(a1,"\n\n", a2,"\n\n", a1+a2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

 [1 2 3 6] 

 [[1. 2. 3. 6.]
 [1. 2. 3. 6.]
 [1. 2. 3. 6.]]


In [153]:
a1.T # Transpose

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [154]:
np.random.seed(1) # Set a seed